services:
  - type: web
    name: lead-management-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: lead-management-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: FRONTEND_URL
        value: https://your-frontend-url.vercel.app

databases:
  - name: lead-management-db
    plan: free
    databaseName: lead_management
